// <auto-generated />
namespace SpooderManCars.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Jellin : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Jellin));
        
        string IMigrationMetadata.Id
        {
            get { return "202009081936206_Jellin"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
