// <auto-generated />
namespace SpooderManCars.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class UndidRacing : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UndidRacing));
        
        string IMigrationMetadata.Id
        {
            get { return "202009111839353_UndidRacing"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
